"""Type stubs for colors module"""

from typing import Union, Sequence, overload
import numpy as np
from numpy.typing import NDArray
from .types import ColorType

ColorInput = Union[ColorType, int, float, str, Sequence[float]]

class Color:
    """Immutable RGBA color optimized for GPU rendering (0.0-1.0 range)"""
    __slots__ = ('_r', '_g', '_b', '_a')
    
    def __init__(self, r: float = 0.0, g: float = 0.0, b: float = 0.0, a: float = 1.0) -> None: ...
    
    @property
    def r(self) -> float: ...
    @property
    def g(self) -> float: ...
    @property
    def b(self) -> float: ...
    @property
    def a(self) -> float: ...
    
    @classmethod
    def from_rgba(cls, r: float, g: float, b: float, a: float = 1.0) -> Color: ...
    @classmethod
    def from_rgb(cls, r: float, g: float, b: float) -> Color: ...
    @classmethod
    def from_rgba255(cls, r: int, g: int, b: int, a: int = 255) -> Color: ...
    @classmethod
    def from_rgb255(cls, r: int, g: int, b: int) -> Color: ...
    @classmethod
    def from_hex(cls, hex_str: str) -> Color: ...
    @classmethod
    def from_hsv(cls, h: float, s: float, v: float, a: float = 1.0) -> Color: ...
    @classmethod
    def from_hls(cls, h: float, l: float, s: float, a: float = 1.0) -> Color: ...
    @classmethod
    def from_gray(cls, gray: float, a: float = 1.0) -> Color: ...
    
    def to_rgba(self) -> tuple[float, float, float, float]: ...
    def to_rgb(self) -> tuple[float, float, float]: ...
    def to_rgba255(self) -> tuple[int, int, int, int]: ...
    def to_rgb255(self) -> tuple[int, int, int]: ...
    def to_hex(self, include_alpha: bool = False) -> str: ...
    def to_hsv(self) -> tuple[float, float, float]: ...
    def to_hls(self) -> tuple[float, float, float]: ...
    def to_array(self) -> NDArray[np.float32]: ...
    
    def with_alpha(self, a: float) -> Color: ...
    def lerp(self, other: Color, t: float) -> Color: ...
    def multiply(self, factor: float) -> Color: ...
    def lighten(self, amount: float = 0.1) -> Color: ...
    def darken(self, amount: float = 0.1) -> Color: ...
    def saturate(self, amount: float = 0.1) -> Color: ...
    def desaturate(self, amount: float = 0.1) -> Color: ...
    def rotate_hue(self, degrees: float) -> Color: ...
    def invert(self) -> Color: ...
    def grayscale(self) -> Color: ...
    
    def __add__(self, other: Color) -> Color: ...
    def __sub__(self, other: Color) -> Color: ...
    def __mul__(self, factor: float) -> Color: ...
    def __rmul__(self, factor: float) -> Color: ...
    def __truediv__(self, factor: float) -> Color: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __iter__(self): ...
    def __getitem__(self, idx: int) -> float: ...
    
    @classmethod
    def transparent(cls) -> Color: ...
    @classmethod
    def white(cls) -> Color: ...
    @classmethod
    def black(cls) -> Color: ...
    @classmethod
    def red(cls) -> Color: ...
    @classmethod
    def green(cls) -> Color: ...
    @classmethod
    def blue(cls) -> Color: ...
    @classmethod
    def cyan(cls) -> Color: ...
    @classmethod
    def magenta(cls) -> Color: ...
    @classmethod
    def yellow(cls) -> Color: ...
    @classmethod
    def orange(cls) -> Color: ...
    @classmethod
    def purple(cls) -> Color: ...
    @classmethod
    def pink(cls) -> Color: ...
    @classmethod
    def gray(cls, level: float = 0.5) -> Color: ...

def normalize_color(color: ColorInput) -> ColorType: ...
def lerp_colors(color1: ColorInput, color2: ColorInput, t: float) -> ColorType: ...
def gradient(colors: list[ColorInput], steps: int) -> list[ColorType]: ...
def batch_colors_to_array(colors: Sequence[ColorInput]) -> NDArray[np.float32]: ...
